plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

exclude:
    - gemfile
    - gemfile.lock
    - gulpfile.babel.js
    - LICENSE.md
    - node_modules
    - package.json
    - package-lock.json
    - README.md
    - src
    - tailwind.config.js
    - netlify.toml
    - docs
    - ext_scripts
    - sudouc.club.gemspec
    - postcss.config.js


url: https://sudouc.club
title: Sudo UC
logo: /favicon.ico